plot4 <- function() {
    source("loadData.R")
    data <- loadData()
    png(filename="plot4.png",width=480, height=480, units="px")
    par(mfrow=c(2,2)) 
    plot(data$DateTime, data$Global_active_power, type='l',ylab="Global Active Power", xlab="")
    plot(data$DateTime, data$Voltage, type="l", ylab="Voltage", xlab="datetime")
    plot(data$DateTime, data$Sub_metering_1, type="n", ylab="Energy sub metering", xlab="")
    lines(data$DateTime, data$Sub_metering_1, col="black")
    lines(data$DateTime, data$Sub_metering_2, col="red")
    lines(data$DateTime, data$Sub_metering_3, col="blue")
    legend("topright",lty="solid", col = c("black","red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
    plot(data$DateTime, data$Global_reactive_power, type="l", ylab="Global_reactive_power", xlab="datetime")
    dev.off()    
}